export default {
  projects: [{ name: '20171025RodZ_S69 mutants', samples: [1], account: 'Jennifer', customer: 'Yingjie', opened: '20171026', finish: '', priority: 'Standard', trackingNumber: '36110205' },
    { name: 'FALL2017/MICRO PURIFIED', samples: [], account: 'Jennifer', customer: 'THU', opened: '20171026', finish: '', priority: 'Standard', trackingNumber: '36109507' },
    { name: 'FALL2017/MICRO PURIFIED', samples: [], account: 'Jennifer', customer: 'THU', opened: '20171026', finish: '', priority: 'Standard', trackingNumber: '36109355' },
    { name: 'FALL2017/MICRO UNPURIFIED', samples: [], account: 'Jennifer', customer: 'THU', opened: '20171026', finish: '', priority: 'Standard', trackingNumber: '36107407' },
    { name: 'FALL2017/MICRO-UNPURIFIED WITH BLANK', samples: [], account: 'Jennifer', customer: 'THU', opened: '20171026', finish: '', priority: 'Standard', trackingNumber: '36106555' },
    { name: 'Phong Lu', samples: [], account: 'Jennifer', customer: 'Phong', opened: '20171026', finish: '', priority: 'Standard', trackingNumber: '36103533' },
    { name: 'FALL2017/BIO221', samples: [], account: 'Jennifer', customer: 'THU', opened: '20171026', finish: '', priority: 'Standard', trackingNumber: '36102618' },
    { name: 'CC', samples: [], account: 'Jennifer', customer: 'Thach', opened: '20171026', finish: '', priority: 'Standard', trackingNumber: '36100629' },
    { name: 'DIL BD #10/25/17 TRT 2 RACKS', samples: [], account: 'Jennifer', customer: 'SD', opened: '20171026', finish: '', priority: 'Standard', trackingNumber: '36098268' },
    { name: 'Cheryl Goldbeck Merck #30-31566249', samples: [], account: 'Jennifer', customer: 'SF', opened: '20171026', finish: '', priority: 'Standard', trackingNumber: '36097346' },
    { name: 'BD_QC_102517_SEA', samples: [], account: 'Jennifer', customer: 'Seattle', opened: '20171026', finish: '', priority: 'Standard', trackingNumber: '36097124' },
    { name: 'Cheryl Goldbeck Merck #30-31566249', samples: [], account: 'Jennifer', customer: 'SF', opened: '20171026', finish: '', priority: 'Standard', trackingNumber: '36096535' },
    { name: 'Meirong', samples: [], account: 'Jennifer', customer: 'Dengke', opened: '20171026', finish: '', priority: 'Standard', trackingNumber: '36095468' },
    { name: 'Myo_ITS3_LR3', samples: [], account: 'Jennifer', customer: 'YOU', opened: '20171026', finish: '', priority: 'Standard', trackingNumber: '36094809' },
    { name: 'MT', samples: [], account: 'Jennifer', customer: 'David', opened: '20171026', finish: '', priority: 'Standard', trackingNumber: '36093368' },
    { name: 'Big Dye Dilution Buffer QC 25Oct2017', samples: [], account: 'Jennifer', customer: 'RTP', opened: '20171026', finish: '', priority: 'Standard', trackingNumber: '36091968' },
    { name: 'Big Dye QC 25Oct2017', samples: [], account: 'Jennifer', customer: 'RTP', opened: '20171026', finish: '', priority: 'Standard', trackingNumber: '36091746' },
    { name: 'e-syt1', samples: [], account: 'Jennifer', customer: 'Andres', opened: '20171026', finish: '', priority: 'Standard', trackingNumber: '36091413' },
    { name: 'ISO QC 25OCT2017', samples: [], account: 'Jennifer', customer: 'RTP', opened: '20171026', finish: '', priority: 'Standard', trackingNumber: '36091046' },
    { name: 'yFZ 004-B C', samples: [], account: 'Jennifer', customer: 'Yunfeng', opened: '20171026', finish: '', priority: 'Standard', trackingNumber: '36090457' },
    { name: 'yFZ 004-b yFZ004-c Sequencing', samples: [], account: 'Jennifer', customer: 'Yunfeng', opened: '20171026', finish: '', priority: 'Standard', trackingNumber: '36089204' },
    { name: 'SUB-90158', samples: [], account: 'Jennifer', customer: 'Anne', opened: '20171026', finish: '', priority: 'Standard', trackingNumber: '36089059' },
    { name: 'Jeff Mazur Cell Design Labs #30-35150356', samples: [], account: 'Jennifer', customer: 'SF', opened: '20171025', finish: '', priority: 'Standard', trackingNumber: '36088837' },
    { name: 'trx_chi', samples: [], account: 'Jennifer', customer: 'Jan', opened: '20171025', finish: '', priority: 'Standard', trackingNumber: '36088248' },
    { name: 'Intro to Bio Fall 2017', samples: [], account: 'Jennifer', customer: 'Dawn', opened: '20171025', finish: '', priority: 'Standard', trackingNumber: '36088026' },
    { name: 'SUB-90157', samples: [], account: 'Jennifer', customer: 'Roger', opened: '20171025', finish: '', priority: 'Standard', trackingNumber: '36087659' },
    { name: 'SUB-90157', samples: [], account: 'Jennifer', customer: 'Roger', opened: '20171025', finish: '', priority: 'Standard', trackingNumber: '36087215' },
    { name: 'SUB-90157', samples: [], account: 'Jennifer', customer: 'Roger', opened: '20171025', finish: '', priority: 'Standard', trackingNumber: '36087437' },
    { name: 'sng-1::BFP', samples: [], account: 'Jennifer', customer: 'Sarah', opened: '20171025', finish: '', priority: 'Standard', trackingNumber: '36087063' },
    { name: 'pCS6-PSD95-Cerulean - CMV-Forward 1', samples: [], account: 'Jennifer', customer: 'Sylvia', opened: '20171025', finish: '', priority: 'Standard', trackingNumber: '36086404' }
  ],
  samples: [{samplename:'303B-His-fat-1-endP_2-new_p256-1',reactionlabel:'AW0001_R',sampletype:'1',primername:'Fat-1-F-660',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'BamHi - Sac I cloned new p256 to 303B-His-fat-1 end P#2',reactionstatus:'10'},
{samplename:'A1_Tube_1_',reactionlabel:'TN0002',sampletype:'3',primername:'FISH1R',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'King',reactionstatus:'10'},
{samplename:'A7_Tube_5_',reactionlabel:'TN0009',sampletype:'3',primername:'FISH1F',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Sockeye',reactionstatus:'10'},
{samplename:'A2_Tube_2_',reactionlabel:'TN0003',sampletype:'3',primername:'FISH1F',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'King',reactionstatus:'10'},
{samplename:'B12_Tube_7_',reactionlabel:'TN0013',sampletype:'3',primername:'FISH1F',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Sockeye',reactionstatus:'10'},
{samplename:'B11_Tube_6_',reactionlabel:'TN0011',sampletype:'3',primername:'FISH1F',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Sockeye',reactionstatus:'10'},
{samplename:'A7_Tube_5_',reactionlabel:'TN0010',sampletype:'3',primername:'FISH1R',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Sockeye',reactionstatus:'10'},
{samplename:'A2_Tube_2_',reactionlabel:'TN0004',sampletype:'3',primername:'FISH1R',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'King',reactionstatus:'10'},
{samplename:'B12_Tube_7_',reactionlabel:'TN0014',sampletype:'3',primername:'FISH1R',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Sockeye',reactionstatus:'10'},
{samplename:'B13_Tube_8_',reactionlabel:'TN0016',sampletype:'3',primername:'FISH1R',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Sockeye',reactionstatus:'10'},
{samplename:'B11_Tube_6_',reactionlabel:'TN0012',sampletype:'3',primername:'FISH1R',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Sockeye',reactionstatus:'10'},
{samplename:'B14_Tube_1_second_',reactionlabel:'TN0018',sampletype:'3',primername:'FISH1R',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'chum',reactionstatus:'10'},
{samplename:'A1_Tube_1_',reactionlabel:'TN0001',sampletype:'3',primername:'FISH1F',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'King',reactionstatus:'10'},
{samplename:'A5_Tube_3_',reactionlabel:'TN0008',sampletype:'3',primername:'FISH1R',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Sockeye',reactionstatus:'10'},
{samplename:'B14_Tube_1_second_',reactionlabel:'TN0017',sampletype:'3',primername:'FISH1F',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'chum',reactionstatus:'10'},
{samplename:'A5_Tube_3_',reactionlabel:'TN0007',sampletype:'3',primername:'FISH1F',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Sockeye',reactionstatus:'10'},
{samplename:'A3_Tube_3_',reactionlabel:'TN0005',sampletype:'3',primername:'FISH1F',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Coho',reactionstatus:'10'},
{samplename:'A3_Tube_3_',reactionlabel:'TN0006',sampletype:'3',primername:'FISH1R',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Coho',reactionstatus:'10'},
{samplename:'B13_Tube_8_',reactionlabel:'TN0015',sampletype:'3',primername:'FISH1F',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Sockeye',reactionstatus:'10'},
{samplename:'Tap1Clone19-8',reactionlabel:'RS0003_R',sampletype:'4',primername:'M13F',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Pick Random white colony',reactionstatus:'10'},
{samplename:'Tap1Clone19-7',reactionlabel:'RS0002_R',sampletype:'4',primername:'M13F',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Pick Random white colony',reactionstatus:'10'},
{samplename:'4KRL-B1',reactionlabel:'KB0002',sampletype:'3',primername:'3245',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate1-B1',reactionstatus:'60'},
{samplename:'4KRL-C1',reactionlabel:'KB0003',sampletype:'3',primername:'3245',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate1-C1',reactionstatus:'60'},
{samplename:'4KRL-D1',reactionlabel:'KB0004',sampletype:'3',primername:'3245',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate1-D1',reactionstatus:'60'},
{samplename:'4KRL-E1',reactionlabel:'KB0005',sampletype:'3',primername:'3245',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate1-E1',reactionstatus:'60'},
{samplename:'4KRL-H1',reactionlabel:'KB0008',sampletype:'3',primername:'3245',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate1-H1',reactionstatus:'60'},
{samplename:'4KRL-A2',reactionlabel:'KB0009',sampletype:'3',primername:'3245',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate1-A2',reactionstatus:'60'},
{samplename:'4KRL-B2',reactionlabel:'KB0010',sampletype:'3',primername:'3245',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate1-B2',reactionstatus:'60'},
{samplename:'4KRL-C2',reactionlabel:'KB0011',sampletype:'3',primername:'3245',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate1-C2',reactionstatus:'60'},
{samplename:'4KRL-D2',reactionlabel:'KB0012',sampletype:'3',primername:'3245',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate1-D2',reactionstatus:'60'},
{samplename:'4KRL-E2',reactionlabel:'KB0013',sampletype:'3',primername:'3245',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate1-E2',reactionstatus:'60'},
{samplename:'4KRL-F2',reactionlabel:'KB0014',sampletype:'3',primername:'3245',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate1-F2',reactionstatus:'60'},
{samplename:'4KRL-G2',reactionlabel:'KB0015',sampletype:'3',primername:'3245',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate1-G2',reactionstatus:'60'},
{samplename:'4KRL-H2',reactionlabel:'KB0016',sampletype:'3',primername:'3245',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate1-H2',reactionstatus:'60'},
{samplename:'4KRL-A3',reactionlabel:'KB0017',sampletype:'3',primername:'3245',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate1-A3',reactionstatus:'60'},
{samplename:'4KRL-B3',reactionlabel:'KB0018',sampletype:'3',primername:'3245',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate1-B3',reactionstatus:'60'},
{samplename:'4KRL-C3',reactionlabel:'KB0019',sampletype:'3',primername:'3245',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate1-C3',reactionstatus:'60'},
{samplename:'4KRL-D3',reactionlabel:'KB0020',sampletype:'3',primername:'3245',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate1-D3',reactionstatus:'60'},
{samplename:'4JHN-E3',reactionlabel:'KB0021',sampletype:'3',primername:'3245',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate1-E3',reactionstatus:'60'},
{samplename:'4JHN-F3',reactionlabel:'KB0022',sampletype:'3',primername:'3245',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate1-F3',reactionstatus:'60'},
{samplename:'4JHN-G3',reactionlabel:'KB0023',sampletype:'3',primername:'3245',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate1-G3',reactionstatus:'60'},
{samplename:'4JHN-H3',reactionlabel:'KB0024',sampletype:'3',primername:'3245',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate1-H3',reactionstatus:'60'},
{samplename:'4JHN-A4',reactionlabel:'KB0025',sampletype:'3',primername:'3245',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate1-A4',reactionstatus:'60'},
{samplename:'4JHN-B4',reactionlabel:'KB0026',sampletype:'3',primername:'3245',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate1-B4',reactionstatus:'60'},
{samplename:'4JHN-C4',reactionlabel:'KB0027',sampletype:'3',primername:'3245',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate1-C4',reactionstatus:'60'},
{samplename:'4JHN-D4',reactionlabel:'KB0028',sampletype:'3',primername:'3245',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate1-D4',reactionstatus:'60'},
{samplename:'4JHN-E4',reactionlabel:'KB0029',sampletype:'3',primername:'3245',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate1-E4',reactionstatus:'60'},
{samplename:'4JHN-F4',reactionlabel:'KB0030',sampletype:'3',primername:'3245',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate1-F4',reactionstatus:'60'},
{samplename:'4JHN-G4',reactionlabel:'KB0031',sampletype:'3',primername:'3245',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate1-G4',reactionstatus:'60'},
{samplename:'4JHN-H4',reactionlabel:'KB0032',sampletype:'3',primername:'3245',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate1-H4',reactionstatus:'60'},
{samplename:'4JHN-A5',reactionlabel:'KB0033',sampletype:'3',primername:'3245',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate1-A5',reactionstatus:'60'},
{samplename:'4JHN-B5',reactionlabel:'KB0034',sampletype:'3',primername:'3245',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate1-B5',reactionstatus:'60'},
{samplename:'4JHN-C5',reactionlabel:'KB0035',sampletype:'3',primername:'3245',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate1-C5',reactionstatus:'60'},
{samplename:'4JHN-D5',reactionlabel:'KB0036',sampletype:'3',primername:'3245',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate1-D5',reactionstatus:'60'},
{samplename:'4JHN-E5',reactionlabel:'KB0037',sampletype:'3',primername:'3245',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate1-E5',reactionstatus:'60'},
{samplename:'4JHN-F5',reactionlabel:'KB0038',sampletype:'3',primername:'3245',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate1-F5',reactionstatus:'60'},
{samplename:'4JHN-G5',reactionlabel:'KB0039',sampletype:'3',primername:'3245',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate1-G5',reactionstatus:'60'},
{samplename:'4JHN-H5',reactionlabel:'KB0040',sampletype:'3',primername:'3245',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate1-H5',reactionstatus:'60'},
{samplename:'PADL-4NBZv3-A1',reactionlabel:'KB0041',sampletype:'3',primername:'8801',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate2-A1',reactionstatus:'60'},
{samplename:'PADL-4NBZv3-A2',reactionlabel:'KB0042',sampletype:'3',primername:'8801',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate2-A2',reactionstatus:'60'},
{samplename:'PADL-4NBZv3-A3',reactionlabel:'KB0043',sampletype:'3',primername:'8801',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate2-A3',reactionstatus:'60'},
{samplename:'PADL-4NBZv3-A4',reactionlabel:'KB0044',sampletype:'3',primername:'8801',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate2-A4',reactionstatus:'60'},
{samplename:'PADL-4NBZv3-A5',reactionlabel:'KB0045',sampletype:'3',primername:'8801',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate2-A5',reactionstatus:'60'},
{samplename:'PADL-4NBZv3-B1',reactionlabel:'KB0046',sampletype:'3',primername:'8801',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate2-B1',reactionstatus:'60'},
{samplename:'PADL-4NBZv3-B2',reactionlabel:'KB0047',sampletype:'3',primername:'8801',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate2-B2',reactionstatus:'60'},
{samplename:'PADL-4NBZv3-B3',reactionlabel:'KB0048',sampletype:'3',primername:'8801',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate2-B3',reactionstatus:'60'},
{samplename:'PADL-4NBZv3-B4',reactionlabel:'KB0049',sampletype:'3',primername:'8801',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate2-B4',reactionstatus:'60'},
{samplename:'PADL-4NBZv3-B5',reactionlabel:'KB0050',sampletype:'3',primername:'8801',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate2-B5',reactionstatus:'60'},
{samplename:'PADL-4NBZv3-C1',reactionlabel:'KB0051',sampletype:'3',primername:'8801',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate2-C1',reactionstatus:'60'},
{samplename:'PADL-4NBZv3-C2',reactionlabel:'KB0052',sampletype:'3',primername:'8801',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate2-C2',reactionstatus:'60'},
{samplename:'PADL-4NBZv3-C3',reactionlabel:'KB0053',sampletype:'3',primername:'8801',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate2-C3',reactionstatus:'60'},
{samplename:'PADL-4NBZv3-C4',reactionlabel:'KB0054',sampletype:'3',primername:'8801',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate2-C4',reactionstatus:'60'},
{samplename:'PADL-4NBZv3-C5',reactionlabel:'KB0055',sampletype:'3',primername:'8801',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate2-C5',reactionstatus:'60'},
{samplename:'PADL-4NBZv3-D1',reactionlabel:'KB0056',sampletype:'3',primername:'8801',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate2-D1',reactionstatus:'60'},
{samplename:'PADL-4NBZv3-D2',reactionlabel:'KB0057',sampletype:'3',primername:'8801',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate2-D2',reactionstatus:'60'},
{samplename:'PADL-4NBZv3-D3',reactionlabel:'KB0058',sampletype:'3',primername:'8801',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate2-D3',reactionstatus:'60'},
{samplename:'PADL-4NBZv3-D4',reactionlabel:'KB0059',sampletype:'3',primername:'8801',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate2-D4',reactionstatus:'60'},
{samplename:'PADL-4NBZv3-D5',reactionlabel:'KB0060',sampletype:'3',primername:'8801',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate2-D5',reactionstatus:'60'},
{samplename:'PADL-4NBZv3-E1',reactionlabel:'KB0061',sampletype:'3',primername:'8801',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate2-E1',reactionstatus:'60'},
{samplename:'PADL-4NBZv3-E2',reactionlabel:'KB0062',sampletype:'3',primername:'8801',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate2-E2',reactionstatus:'60'},
{samplename:'PADL-4NBZv3-E3',reactionlabel:'KB0063',sampletype:'3',primername:'8801',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate2-E3',reactionstatus:'60'},
{samplename:'PADL-4NBZv3-E4',reactionlabel:'KB0064',sampletype:'3',primername:'8801',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate2-E4',reactionstatus:'60'},
{samplename:'PADL-4NBZv3-E5',reactionlabel:'KB0065',sampletype:'3',primername:'8801',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate2-E5',reactionstatus:'60'},
{samplename:'PADL-4NBZv3-F1',reactionlabel:'KB0066',sampletype:'3',primername:'8801',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate2-F1',reactionstatus:'60'},
{samplename:'PADL-4NBZv3-F2',reactionlabel:'KB0067',sampletype:'3',primername:'8801',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate2-F2',reactionstatus:'60'},
{samplename:'PADL-4NBZv3-F3',reactionlabel:'KB0068',sampletype:'3',primername:'8801',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate2-F3',reactionstatus:'60'},
{samplename:'PADL-4NBZv3-F4',reactionlabel:'KB0069',sampletype:'3',primername:'8801',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate2-F4',reactionstatus:'60'},
{samplename:'PADL-4NBZv3-F5',reactionlabel:'KB0070',sampletype:'3',primername:'8801',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate2-F5',reactionstatus:'60'},
{samplename:'PADL-4NBZv3-G1',reactionlabel:'KB0071',sampletype:'3',primername:'8801',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate2-G1',reactionstatus:'60'},
{samplename:'PADL-4NBZv3-G2',reactionlabel:'KB0072',sampletype:'3',primername:'8801',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate2-G2',reactionstatus:'60'},
{samplename:'PADL-4NBZv3-G3',reactionlabel:'KB0073',sampletype:'3',primername:'8801',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate2-G3',reactionstatus:'60'},
{samplename:'PADL-4NBZv3-G4',reactionlabel:'KB0074',sampletype:'3',primername:'8801',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate2-G4',reactionstatus:'60'},
{samplename:'PADL-4NBZv3-G5',reactionlabel:'KB0075',sampletype:'3',primername:'8801',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate2-G5',reactionstatus:'60'},
{samplename:'PADL-4NBZv3-H1',reactionlabel:'KB0076',sampletype:'3',primername:'8801',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate2-H1',reactionstatus:'60'},
{samplename:'PADL-4NBZv3-H2',reactionlabel:'KB0077',sampletype:'3',primername:'8801',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate2-H2',reactionstatus:'60'},
{samplename:'PADL-4NBZv3-H3',reactionlabel:'KB0078',sampletype:'3',primername:'8801',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate2-H3',reactionstatus:'60'},
{samplename:'PADL-4NBZv3-H4',reactionlabel:'KB0079',sampletype:'3',primername:'8801',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate2-H4',reactionstatus:'60'},
{samplename:'PADL-4NBZv3-H5',reactionlabel:'KB0080',sampletype:'3',primername:'8801',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate2-H5',reactionstatus:'60'},
{samplename:'4KRL-A1',reactionlabel:'KB0001',sampletype:'3',primername:'3245',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate1-A1',reactionstatus:'60'},
{samplename:'4KRL-F1',reactionlabel:'KB0006',sampletype:'3',primername:'3245',vector:'',returnrequirment:'Yes',isdiscard:'No',comments:'Plate1-F1',reactionstatus:'60'}]
}
